apiVersion: v1
kind: Secret
metadata:
  name: orders-db
type: Opaque
stringData:
  DB_HOST: "dev-postgres-dev.cndiwln8aldh.us-east-1.rds.amazonaws.com"      # e.g. my-rds-staging.xxxxxx.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: "app_db"
  DB_USER: "app_admin"
  DB_PASSWORD: "ahYW3mLA|b)rU##leb:TzZ.Ie_q!"