name: App CI (build, test, scan, push)

on:
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/app-ci.yml"
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-ci.yml"

permissions:
  contents: read

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/iac-ci-demo-app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "app/requirements.txt"

      - name: Install app dependencies
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov ruff

      - name: Lint with ruff
        working-directory: app
        run: |
          ruff check .

      - name: Run tests with coverage
        working-directory: app
        run: |
          pytest --cov=main --cov-report=term-missing

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:latest \
            app

      # scan image with Trivy      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          vuln-type: "os,library"

          #Push image
      - name: Push image to Docker Hub (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest