apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  template:
    spec:
      containers:
        - name: orders-api
          env:
            - name: PORT
              value: "8080"

            # Pull DB connection info from the RDS Secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: DB_PASSWORD